title: "λ„¤μ΄λ²„νμ΄ μ£Όλ¬Έν• μ„λΉ„μ¤ API κ°€μ΄λ“"
labels: ["documentation", "naverpay"]
category: "Inspection Request"

body:
  - type: markdown
    attributes:
      value: |
        # π“¦ λ„¤μ΄λ²„νμ΄ μ£Όλ¬Έν• μ„λΉ„μ¤ API κ°€μ΄λ“
        μ•„λ ν…ν”λ¦Ώμ— λ§μ¶° λ‚΄μ©μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”.
