title: "[검수요청] 개발 환경 검수 요청드립니다."
body:
  - type: markdown
    attributes:
      value: |
        개발 환경에서의 API 연동 개발이 완료되었다면 아래 정보를 기입해 주세요.

        ## 1️⃣ 가맹점 정보 입력하기
        ※ 가맹점ID 는 네이버페이센터 > 내정보 > 가입정보변경 > 페이센터ID 경로에서 확인하실 수 있습니다.

  - type: input
    id: merchant_id
    attributes:
      label: "가맹점 ID"
      placeholder: "_np_xxxxxx_"

  - type: markdown
    attributes:
      value: |
        ## 2️⃣ API 연동 및 호출 현황 작성하기  
        ※ Trace ID는 응답 메시지의 `GNCP-GW-Trace-ID` 헤더에서 확인 가능합니다.  
        ※ 모든 API를 연동할 필요는 없으며, 성공 호출된 Trace ID만 기입해 주세요.

  - type: markdown
    attributes:
      value: "### 주문조회"
  - type: textarea
    id: order_change_list
    attributes:
      label: "변경 상품 주문 내역 조회"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: order_detail
    attributes:
      label: "상품 주문 상세 내역 조회"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: order_no_list
    attributes:
      label: "상품 주문 번호 목록 조회"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: conditional_order_detail
    attributes:
      label: "조건형 상품 주문 상세 내역 조회"
      placeholder: "Trace ID 입력"

  - type: markdown
    attributes:
      value: "### 발주/발송"
  - type: textarea
    id: order_confirm
    attributes:
      label: "발주 확인 처리"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: ship_delay
    attributes:
      label: "발송 지연 처리"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: ship
    attributes:
      label: "발송 처리"
      placeholder: "Trace ID 입력"

  - type: markdown
    attributes:
      value: "### 취소"
  - type: textarea
    id: cancel_request
    attributes:
      label: "취소 요청"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: cancel_approve
    attributes:
      label: "취소 요청 승인"
      placeholder: "Trace ID 입력"

  - type: markdown
    attributes:
      value: "### 반품"
  - type: textarea
    id: return_request
    attributes:
      label: "반품 요청"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: return_approve
    attributes:
      label: "반품 승인"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: return_deny
    attributes:
      label: "반품 거부(철회)"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: return_hold
    attributes:
      label: "반품 보류"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: return_hold_cancel
    attributes:
      label: "반품 보류 해제"
      placeholder: "Trace ID 입력"

  - type: markdown
    attributes:
      value: "### 교환"
  - type: textarea
    id: exchange_pickup
    attributes:
      label: "교환 수거 완료"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: exchange_reship
    attributes:
      label: "교환 재배송 처리"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: exchange_deny
    attributes:
      label: "교환 거부(철회)"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: exchange_hold
    attributes:
      label: "교환 보류"
      placeholder: "Trace ID 입력"
  - type: textarea
    id: exchange_hold_cancel
    attributes:
      label: "교환 보류 해제"
      placeholder: "Trace ID 입력"

  - type: markdown
    attributes:
      value: "### 리뷰"
  - type: textarea
    id: review_lookup
    attributes:
      label: "리뷰 조회"
      placeholder: "Trace ID 입력"
