title: "[검수요청] 개발 환경 검수 요청드립니다."
labels:
  - "검수요청"

body:
  - type: textarea
    id: api_status
    attributes:
      label: "아래 양식을 그대로 작성해 주세요"
      value: |
        개발 환경에서의 API 연동 개발이 완료되었다면 아래 정보를 기입해주시면 됩니다.

        1️⃣ 가맹점 정보 입력하기
        2️⃣ API 연동 및 호출 현황 작성하기

        ---
        ## 1️⃣ 가맹점 정보 입력하기
        - 가맹점 쇼핑몰 URL : 

        ## 2️⃣ API 연동 및 호출 현황 작성하기
        연동하시는 API 의 우측에 Trace ID 를 기입해주시면 됩니다.

        > ※  Trace ID는 응답 메시지의 GNCP-GW-Trace-ID 헤더에서 확인하실 수 있습니다.
        > 제공하는 모든 API 를 연동하지 않아도 무방합니다.

        > e.g.  
        > - [x] 변경 상품 주문 내역 조회 : sample-trace-id
