title: "[문의] {중괄호를 지우고 문의 내용을 작성해주세요}"
body:
  - type: textarea
    id: api_status
    attributes:
      label: "아래 양식을 그대로 작성해 주세요"
      value: |
        ### 문의 배경
        <!-- 문의하시는 배경을 작성해주세요. -->

        ---
        ### 문의 상세 내용
        <!-- 문의하시는 내용을 상세히 작성해주세요. -->
        ⚠️문의 내용에 가맹점 담당자의 개인정보나 보안이 필요한 민감 정보로 공개를 원하지 않으시는 경우에는  <br/> `dl_techsupport@navercorp.com` 주소로 문의해주시기 바랍니다.

        
        ---
        ### 관련 첨부자료
        #### 캡쳐 화면 <br/><br/><br/><br/>
        <!-- 문의 확인에 필요한 캡쳐 화면을 포함해주세요. -->

        #### 참조 링크 <br/><br/><br/><br/>
        <!-- 문의가 발생하고 있는 링크나 관련 참조 링크를 포함해주세요. -->

        #### 오류 내용 <br/><br/><br/><br/>
        <!-- 발생하고 있는 오류 내용이나 캡쳐를 포함해주세요. -->
