title: "[문의] {중괄호를 지우고 문의 내용을 작성해주세요}"
body:
  - type: textarea
    id: api_status
    attributes:
      label: "아래 양식을 그대로 작성해 주세요"
      value: |
        ### 문의 배경

         
        ### 문의 상세 내용

        ⚠️문의 내용에 가맹점 담당자의 개인정보나 보안이 필요한 민감 정보로 공개를 원하지 않으시는 경우에는 `dl_techsupport@navercorp.com` 메일주소로 문의해주시기 바랍니다.

        ### 관련 첨부자료
        #### 캡쳐 화면


        #### 오류 내용
